### ISSUE TITLE
Difference HEAD <-> Master?

### ISSUE THREAD

**Issue by Newar417** [moocowmoo/dashman#19]
I get this when I try to sync: 

> dashman version 0.1.25 (25-g10d3dec) - 2017-4-1 Saturday 15:35:15 CEST
Fetching origin
No local changes to save
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at 10d3dec bugfix - masternodeaddr -> externalip
Up to date.

**Comment by moocowmoo** [comment]
that's not an error. it's saying it's up-to-date.

**Comment by Newar417** [comment]
Not saying that it's an error. Just confusingto me :-)

I also get these:

>Fetching origin
remote: Counting objects: 4, done.
remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 1
Unpacking objects: 100% (4/4), done.
From https://github.com/moocowmoo/dashman
   6aabce1..5b469f6  master     -> origin/master
No local changes to save
Already on 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 5b469f6 bugfix - fix progress/estimate remaining render
Up to date.
