### ISSUE TITLE
Download percentage error - 107%

### ISSUE THREAD

**Issue by gabrielboliveira** [moocowmoo/dashman#22]
Well, this is not an stopping issue, but a bug when installing on Raspberry Pi 3, Raspbian April 2017 release. It shows more than 100% percentage of downloading, then aprox. 108% finished downloading and followed the process

<img width="610" alt="captura de tela 2017-05-18 as 00 34 21" src="https://cloud.githubusercontent.com/assets/11093090/26185524/eac35ef4-3b61-11e7-8894-8ebe347f714f.png">

**Comment by moocowmoo** [comment]
repaired in 5b469f6

thanks for the notify!
