### ISSUE TITLE
line 349: [: too many arguments

### ISSUE THREAD

**Issue by Solaso** [moocowmoo/dashman#25]
It worked fine, but yesterday I see errors. Please advise me, what should do. Thank you
dashman version 0.1.25 (34-g9dd11ff) - Fri Aug  4 16:40:21 MSK 2017
gathering info, please wait... /home/compas/dashman/lib/dashman_functions.sh: line 349: [: too many arguments

**Comment by moocowmoo** [comment]
It looks like more than one `dashd` is running?  if it's still happening, email the output of `pidof dashd` to me at moo@masternode.me.
