### ISSUE TITLE
Just checking: Am I the only with these issues? (since April '17)

### ISSUE THREAD

**Issue by Newar417** [moocowmoo/dashman#26]
`dashnode@zotac:/dashman$ ./dashman status
dashman version 0.1.25 (35-g908572c) - 2017年  8月 11日 金曜日 12:18:43 CEST
gathering info, please wait... 
Could not find latest version from https://www.dash.org/downloads/ -- Exiting.
dashnode@zotac:/dashman$ ./dashman restart
dashman version 0.1.25 (35-g908572c) - 2017年  8月 11日 金曜日 12:19:06 CEST

restart dashd? [y/N] y
 --> Stopping dashd. Please wait...DONE!
 --> Deleting cache files, debug.log... DONE!
 --> Starting dashd... DONE!
 --> Waiting for dashd to respond...DONE!
 --> dash-cli getinfo
error: couldn't connect to server

Exiting.
`

**Comment by moocowmoo** [comment]
I'd guess it's a permissions issue.  Maybe running something as root then
another as a normal user?

Meet me in dashnation slack and I'll chat with you sometime.

https://dash-nation-invite.herokuapp.com/

**Comment by Newar417** [comment]
By setting the curl time out to a very long time (80) both messages are gone. I guess, my internet sucks.
dashman_functions.sh
line 29
