### ISSUE TITLE
Scripts exiting with an error.

### ISSUE THREAD

**Issue by alfredch** [moocowmoo/dashman#8]
I get this error on Linux Ubuntu 14.04:
./dashman install
dashman version 0.1.20 (0.1.20) - Fri Sep  2 06:12:23 EDT 2016
gathering info, please wait...
Could not find latest version from https://www.dash.org/downlaods/ -- Exiting.

**Comment by moocowmoo** [comment]
I don't find that url in the source. It looks like a local edit.

try doing: `./dashman sync` to remove any local edits.

Then try `./dashman install`

**Comment by alfredch** [comment]
Problem still exists after the sync:
![image](https://cloud.githubusercontent.com/assets/7837789/18201210/1aa2091e-7109-11e6-9a7e-f9a09ff36941.png)

**Comment by moocowmoo** [comment]
That is the correct url. 

What does `curl https://www.dash.org/downloads/ | grep linux` show?

**Comment by alfredch** [comment]
It can find the file, but the literal 'linux' is not in downloads HTML

**Comment by alfredch** [comment]
Maybe it is because he asks to complete the CAPTCHA.

**Comment by moocowmoo** [comment]
It may be cloudflare requesting human proof.  Try again now.

**Comment by alfredch** [comment]
Still stuck in requesting human proof.

**Comment by moocowmoo** [comment]
Please capture the page for me and place it in a zerobin paste.  https://zerobin.net/

`curl https://www.dash.org/downloads/ > downloads.html ; less downloads.html`

**Comment by moocowmoo** [comment]
I've created a rule for that page. Please try again.

**Comment by alfredch** [comment]
Synced again, but still captcha problem.
I send you the output later.

**Comment by moocowmoo** [comment]
Please try again now.

The issue is with cloudflare and I cannot reproduce.

**Comment by alfredch** [comment]
Doesn't work. The problem is right now i cannot copy paste from the Linux to my PC. I can only send you this screenshot with the tail of the HTML:
![image](https://cloud.githubusercontent.com/assets/7837789/18202294/7d2e7efe-710f-11e6-878c-ccf347d410ed.png)

**Comment by alfredch** [comment]
Mabe it's because that IP is blacklisted somehow?

**Comment by moocowmoo** [comment]
I'm not finding that ip or Ray ID.

Where is this server located?  What is it's ip address?

**Comment by alfredch** [comment]
Its IP is 198.50.159.204, in Montreal Canada.(https://www.pulseservers.com)  It is a VPS

**Comment by alfredch** [comment]
My VPN previously run a tor exit node. That might be the reason why CloudFlare requires Capcha now.
See: 
[https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-]
On the other hand, tor server is stopped since 3 weeks.  When does Cloudflare unblock those IPs?
