### ISSUE TITLE
Script should not test for netcat6 in recent Ubuntu releases

### ISSUE THREAD

**Issue by alfredch** [moocowmoo/dashman#9]
Ubuntu 16.04 LTS (Xenial) has no netcat6 package any more, because nc now support IPV6.
Therfore, testing for package netcat6 is obsolete and stops the script.
./lib/dashman_functions.sh       MISSING_DEPENDENCIES="$MISSING_DEPENDENCIES netcat6"

**Comment by 0xfffxfff** [comment]
How did you go about solving this? Manually?

**Comment by alfredch** [comment]
I solved it by modifying the script.
I did a fresh install last week with the latest. The issue seems to be solved.

**Comment by 0xfffxfff** [comment]
Interesting, I'm on the latest branch as well – 0.1.23 @ 1601750
But I get this on Ubuntu 16.04.1 LTS
```
dashman status
missing dependency:  netcat6
 --> sudo apt-get install  netcat6
```

**Comment by 0xfffxfff** [comment]
Okay, got it. By default the package `netcat-traditional` is installed, which uses different syntax?

I had to install `netcat-openbsd`
```
sudo apt-get install netcat-openbsd
```
and configure it with
```
sudo update-alternatives --config nc
```
